### ISSUE TITLE
Wasm32 porting related problems

### ISSUE THREAD

**Issue by edwin0cheng** [sebcrozet/nphysics#100]
I successfully use nphysics and ncollide in wasm32 target :

[live demo] (https://edwin0cheng.github.io/unigame_demo/)

However, there are some minor issues:

* rand crate version 3 do not work in wasm target (4.1 + will works)
* rustc-serialize do not work too (maybe change it to serde?)
* The performance is a little bit worse than bullet js port. I tried 500 boxes which only 10fps but ammo.js (bullet wasm) could go up to 60fps), I am going to investigate more.

The good parts:
* Size! The size is around 300k (included my webgl code), bullet port is around 600k , 100% size reduced.

**Comment by sebcrozet** [comment]
Thank you for making this demo and for the feedbacks! I will update `rand` and get rid of `rustc-serialize` in the next release. Regarding performances, I am not surprised that `nphysics` is slower than a `bullet` port, though a gap of 50fps seems quite a lot. I have not focused too much on performances for the moment though I will get to it after March.
