### ISSUE TITLE
What is the main goal of it?

### ISSUE THREAD

**Issue by BadFactor** [sebcrozet/nphysics#102]
Hi,...first of all!

this should present some main question, that everyone has if they are new and want to stick with nphysics!

So lets say,.. its a space for them to ask more questions about it!

Are there any plans to expand the "SDK"?

What should Nphysics represent? Is it something like PhysX from Nvidia or what ?

Can we expect something like a fluid simulation or other cool stuff, that we can use in maybe our Gameengine or in other Software Solutions?

And how far you guys with nphysics?

**Comment by sebcrozet** [comment]
Hi!

nphysics is a physics engine: a library that allows you to add physical behaviors and collision detection to solids in your 2D or 3D game (or animation for example). So it is indeed the same kind of library as PhysX, Havock, Bullet, ODE, Box2D, etc. There are two crates that share almost the same codebase: `nphysics2d` for 2D physics simulation and `nphysics3d` for 3D physics simulation. The goal of those crates is to provide the best (even though we are not yet the best) solution for physics simulation in the context of video games, animation, and robotics. In particular, we include some features that are not present in other physics engine (a stable implementation of multibodies) which are essential for accurate robotics simulation.

SPH-based fluid simulation and soft bodies are not implemented on nphysics yet. They will be at some point but for the moment I focus on completing features related to rigid bodies, and on performances.

**Comment by BadFactor** [comment]
thanks for the answer, hopefully it will get better and better in performance, just want kick some asses with that library ;) 

have a nice day!
