### ISSUE TITLE
Remove old nphysics crate

### ISSUE THREAD

**Issue by Laaas** [sebcrozet/nphysics#109]
The old nphysics crate here should be removed: https://crates.io/crates/nphysics

It's very confusing

**Comment by sebcrozet** [comment]
I would if I could. Unfortunately it is not currently possible to remove a crate from `crates.io`.
The best I could do would be to yank all the versions of `nphysics` though.

**Comment by jonas-schievink** [comment]
Additionally, you could push an empty crate as a new version, with a readme and description that says not to use it

**Comment by sebcrozet** [comment]
I've yanked all version of the nphysics crate and updated the description to say it is deprecated.
Though I did not let a non-yanked version with a specific README since I don't want anyone to even add the dependency.
