### ISSUE TITLE
Unsafe code is unsafe.

### ISSUE THREAD

**Issue by quadrupleslap** [sebcrozet/nphysics#116]
```
impl<N: Real> Force3<N> {
    ...
    #[inline]
    pub fn as_vector(&self) -> &Vector6<N> {
        unsafe { mem::transmute(self) }
    }
}
```

But this is `repr(Rust)`, so by the [nomicon](https://doc.rust-lang.org/nomicon/repr-rust.html),

> the layout of data is not by default specified in Rust.

**Comment by sebcrozet** [comment]
Correct, it should be marked as `repr(C)` insetad.

**Comment by quadrupleslap** [comment]
Are you sure that's enough? Memory alignment is really confusing for me.

**Comment by sebcrozet** [comment]
Yes, this should be enough, as this guaranties the layout to be C-compatible. Since `Vector6<N>` is also `#[repr(C)]`, they will both have the same layout/memory alignment properties

**Comment by vitvakatu** [comment]
I suppose this issue should be closed now as `Force3` is `#[repr(C)]` now.
