### ISSUE TITLE
Implement ghost- aka. sensor-objects

### ISSUE THREAD

**Issue by qrlpx** [sebcrozet/nphysics#20]
Objects who report overlaps/collisions with other objects, but don't actually affect them.
Bullet3d calls them ghost-objects; for Box2d and Chipmunk2d, they're sensors.

**Comment by Connorcpu** [comment]
This isn't the best, but as a workaround you could keep a separate CollisionWorld from ncollide just for handling those overlap queries.

**Comment by sebcrozet** [comment]
I've been working on this during the past few weeks. I have a first working [demo](https://github.com/sebcrozet/nphysics/blob/2e52d09c1b4c85bde2b9d4d47b0f04c9aa0425d3/examples3d/sensor.rs) now (not merged with master yet), so hopefully I'll be able to release a first implementation in a week or so!
