### ISSUE TITLE
Can't build examples

### ISSUE THREAD

**Issue by GregoryTravis** [sebcrozet/nphysics#285]
I'm getting a lot of these when building examples:

the trait bound `N: nphysics::nalgebra::RealField` is not satisfied

I followed a suggestion here which let it get further but it still gets some of the trait bound errors:
https://discourse.nphysics.org/t/compiler-errors-when-upgrading-to-0-22/546

I'm running:
$ cargo --version
cargo 1.54.0 (5ae8d74b3 2021-06-22)
$ rustc --version
rustc 1.54.0 (a178d0322 2021-07-26)

**Comment by sebcrozet** [comment]
The examples of nphysics haven’t been updated for a while now since nphysics is being deprecated in favor of [rapier](https://github.com/dimforge/rapier).
