### ISSUE TITLE
Simulations are no longer deterministic.

### ISSUE THREAD

**Issue by sebcrozet** [sebcrozet/nphysics#30]
The HashMap api related to custom hasher is not yet accessible from a stable Rust compiler. Thus, we cannot use a non-random hasher. This should be fixable in future version of the compiler.

**Comment by MrMormon** [comment]
Are there any workarounds? Or guarantees for small numbers of dynamic actors?

**Comment by sebcrozet** [comment]
Unfortunately, I could not find any workaround… I guess the only solution is to wait until it is no longer deprecated (as of today it is still commented as `Unstable: hasher stuff is unclear`).

**Comment by MrMormon** [comment]
Should I copy/reference this issue in ncollide's repo? There's a similar comment in the source there.

**Comment by WaDelma** [comment]
Has this been resolved now that HashMap hasher API is stable?

**Comment by sebcrozet** [comment]
Thanks for reminding me. It is fixed now!

**Comment by MrMormon** [comment]
This finally makes Rust and nphysics usable for some of my own projects!

**Comment by marcusjwhelan** [comment]
You should definitely advertise that this is a deterministic physics engine.
