### ISSUE TITLE
src/math.rs is empty?!

### ISSUE THREAD

**Issue by m-bra** [sebcrozet/nphysics#36]
It's weird that this file contains zero lines.
Also, I tried building the doc, that failed and several errors showed up stating that `math*` is missing.

I doubt this is a coincidence. Maybe an error uploading the file?

**Comment by sebcrozet** [comment]
This file should not exist, I will remove it.

Building the documentation with `cargo doc` will invariably fail with unresolved import errors. You have to select the variant of `nphysics` you want to build the doc for. For example for the 3d simulator using 64 bit floating point values, you need to use `cargo doc --features "3df32"`.

**Comment by m-bra** [comment]
Oh okay, this makes sense. Thanks!
