### ISSUE TITLE
Is anyone already looking into the failing volumetric::volumetric_convex::test::test_inertia_tensor test?

### ISSUE THREAD

**Issue by MichaelRiss** [sebcrozet/nphysics#43]
For a while now the `volumetric::volumetric_convex::test::test_inertia_tensor` is failing.

I tried to track it down, but my `println!( "... {:?}", ... );` attempts failed once I got to `ncollide::ncollide_transform::convex_hull::get_initial_mesh()`.
The eigenvector calculation returns objects that cannot be printed via the `{:?}` formatting because the `Debug` trait is missing for them and ... I just cannot figure out how and where to fix it.
After the eigenvector values get weaved into `points` they are suddenly all `NaN` values.
So, something seems to be failing in the eigenvector section.

The other thing I saw is, that there was a major change in `nalgebra` with the QR algorithm. It could be that this was the crucial change that broke the `nphysics` test.

Beyond that, I'm at a loss what to do, did anyone already look into that? Any ideas/pointers for me?

**Comment by MichaelRiss** [comment]
In the mean time I made some progress. I managed to somehow add the Debug trait to the Outer trait of nalgebra (https://github.com/sebcrozet/nalgebra/pull/162) and this enabled println! debug output in ncollide (https://github.com/MichaelRiss/ncollide/tree/with_debug_println). 

With this debugging toolkit I then traced the failing test indeed to the qr eigen computation in nalgebra. It seems that the algorithm has problems with diagonal matrices. I provided a test case (https://github.com/sebcrozet/nalgebra/pull/163). Maybe @dshizzle can also take a look at it as he still may have the code present in his mind?

**Comment by dshizzle** [comment]
Thank you for pointing out this issue. Please check if sebcrozet/nalgebra#164 fixes this bug.

**Comment by MichaelRiss** [comment]
Yes, it does. Great! Thanks!

**Comment by sebcrozet** [comment]
The fix has been merged and the new version of nalgebra published.
Closing this. Thanks!
