### ISSUE TITLE
Documentation pointing to the wrong variant

### ISSUE THREAD

**Issue by jhasse** [sebcrozet/nphysics#45]
Hi,

this is just a very minor issue: On http://nphysics.org/doc/nphysics2df64/ it says to add
```
[dependencies.nphysics3df32]
git = "https://github.com/sebcrozet/nphysics"
```
to the Cargo.toml, but shouldn't it be 2df64?

Another thing I noticed is, that Rust is written in small letters on that page: rust.

**Comment by jhasse** [comment]
Also just ran into this 404: http://nphysics.org/doc/nphysics/world/struct.World.html

**Comment by jFransham** [comment]
Lots of links in the documentation point to `nphysics/*` when they should point to `nphysics[dimension]d[type]`

**Comment by Kerosene2000** [comment]
Up ?
The [documentation (`add_body` become `add_rigid_body`)](http://nphysics.org/doc/nphysics2d/world/struct.World.html#method.add_body) is not up to date 😢

**Comment by sebcrozet** [comment]
It should work and be up to date now!

**Comment by Kerosene2000** [comment]
Thank you !
