### ISSUE TITLE
Does not compile with my nightly

### ISSUE THREAD

**Issue by mrkgnao** [sebcrozet/nphysics#49]
**Version**

```
$ rustc --version
rustc 1.9.0-nightly (d7a71687e 2016-03-24)
```

**What I was trying to do**

I just want to test out `gravity.rs` to get a feel for how this library works. So I made a new project, copied the contents of `gravity.rs` from the repo into a file and added `nphysics` to my deps. Then I ran `cargo build`, which gave me this error:

```
/home/mrkgnao/.cargo/registry/src/github.com-88ac128001ac3a9a/nphysics-0.1.0/src/lib.rs:93:14: 93:24 error: expected ident, found `"nalgebra"`
/home/mrkgnao/.cargo/registry/src/github.com-88ac128001ac3a9a/nphysics-0.1.0/src/lib.rs:93 extern crate "nalgebra" as na;
```

so I forked and cloned the `nphysics` repo to see if I could build it myself. When I run `cargo build`, I get a bunch of errors complaining about missing `extern crate math` everywhere, and then a ton of errors I don't understand ([all errors pasted here](http://lpaste.net/6779621415927676928)).

**Comment by sebcrozet** [comment]
About the errors when you ran `cargo build` yourself: `nphysics` cannot be compiled without at least one feature activated so you have to run, e.g., cargo build --features "3df32" if you want 3D and 32-bit precision.

This is not idiomatic at all, but to use `nphysics` on your own project, you actually have to depend on `nphysics3df32`,   or `nphysics3df64`, or `nphysics2df32`, or `nphysics2df64` on your `Cargo.toml`.

**Comment by MovingtoMars** [comment]
How about adding
```
default = ["2df32"]
```

in the `[features]` section of Cargo.toml?

**Comment by WaDelma** [comment]
There should be part of the README that mentions how to build nphysics itself. I tried to build nphysics myself to see if I could start contributing on it and I thought that current master is just broken. (I am using feb1e6fd for my project, because that seemed to work on stable.)

**Comment by sebcrozet** [comment]
Closing htis. This is no longer applicable given the current architecture of nphysics.
