### ISSUE TITLE
Collision groups self-colliding

### ISSUE THREAD

**Issue by trolleyman** [sebcrozet/nphysics#65]
First, let me just say thanks for creating the nphysics library - simple to use and very performant!

Now, the bug. I have been developing with nphysics for a few weeks now in my [repo](https://github.com/trolleyman/neat) and I have come across a problem when trying to create a simple table. To run the code:

```
git clone https://github.com/trolleyman/neat
cd neat
cargo run --release -- -pv
```

`-p` pauses the simulation
`-v` makes it verbose
`F1` to resume the simulation
`F2` to step the simulation

I create the entities in [GameStateBuilder](https://github.com/trolleyman/neat/blob/master/src/game/state_builder.rs#L277-L345). This calls EntityBuilder a few times which calls [Entity::with_matrix](https://github.com/trolleyman/neat/blob/master/src/game/entity.rs#L222-L307). This adds the rigid bodies to the world and adds the joints. I set the collision groups [here](https://github.com/trolleyman/neat/blob/master/src/game/entity.rs#L264-L270), and you should see from the output that it adds each body to the collision group and disables self collision just in case. Any reason why it doesn't work?

Oh also, would it be possible to modify ncollide to allow for a potentially infinite pool of collision groups? I kind of need this to implement entities that don't glitch out completely...

**Comment by sebcrozet** [comment]
For performance reasons, there is no plan to allow an infinite number of collision groups. To overcome this limitation, the next release of `ncollide` will give the user the ability to add his own filters. Also keep in mind that disabling self-collision will only prevent a rigid body to collide with itself: it will not prevent a rigid body to collide with another body linked to it with a joint.

If I understand correctly, you are trying to create a concave geometry (the table) from its convex components. The `Fixed` joint + collision groups combinaison is not the right method here unless you actually want the tables to be dynamically breakable. Instead, you should create only one rigid body and give it a `Compound` geometry that will contain five cuboids! You will find an example of `Compound` initialization [there](https://github.com/sebcrozet/nphysics/blob/master/examples3d/compound.rs#L36-L43) (having to use `Arc` and `Box` explicitly is quite ugly but it will get simpler in the next release of `ncollide`).

In any cases, keep the use of joints as a last ressort: the more joints you use, the harder it will be for the constraints solver to stabilize the system. Also the current implementation of joints on nphysics is not so great in term of stability.

By the way, I

**Comment by trolleyman** [comment]
Ohhh I see...

Thanks for replying. That's a good idea, I won't even need the collision groups!
