### ISSUE TITLE
nphysics no longer compiles on nightly

### ISSUE THREAD

**Issue by trolleyman** [sebcrozet/nphysics#67]
When trying to compile nphysics on a nightly created on or after `2016-04-14`, the compiler errors. Before this date it is fine. This error is produced:

```
   Compiling nphysics3d v0.2.2 (https://github.com/sebcrozet/nphysics.git#b379109f)
error: internal compiler error: ../src/librustc_trans\debuginfo\type_names.rs:155: debuginfo: Trying to create type name for unexpected type: <na::Pnt3<f32> as nc::ncollide_math::Point>::Vect
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', ../src/libsyntax\errors/mod.rs:575
```

**Comment by sebcrozet** [comment]
This is very unfortunate… It's a bug on the compiler so I am not sure I can do anything about it! Perhaps a similar bug (related to associated types) has already been reported on the rustc repo.?

**Comment by trolleyman** [comment]
Just wanted to let you know, see if you knew more about it than me

**Comment by sebcrozet** [comment]
Well I knew _something_ was going on with the nightlies because some examples of ncollide trigger the same kind of ICE. But I did not investigate further because I assume this will hopefully be fixed before the next release/beta. Thanks for showing me nphysics is completely affected as well!

**Comment by trolleyman** [comment]
My bad, turns out it compiles fine but I was reading the logs wrong. It's _my_ crate that isn't compiling...

**Comment by trolleyman** [comment]
Turns out I was wrong again! This test case fails to compile on the latest nightly:

```
extern crate nphysics3d;

pub fn main() {
	nphysics3d::world::World::new().step(1.0);
}
```

Issue is on the rust-lang repo [#33096](https://github.com/rust-lang/rust/issues/33096).

**Comment by gmorenz** [comment]
It now compiles on the latest nightly, I think this issue can be closed.
