### ISSUE TITLE
Support temporarily removing bodies from the physics world

### ISSUE THREAD

**Issue by Ralith** [sebcrozet/nphysics#90]
I'm working on a VR project, where the player will routinely pick up physics objects (causing them to be attached to their tracked controller and no longer participate in collision detection or dynamics) for short periods and then release them (causing them to re-enter the simulation at a nearby position and velocity).

At first, it seems like `World::remove_rigid_body` is the right tool, but there are a few issues:
- The body might have attached sensors, and it's unclear what happens to those
- It calls `RigidBody::delete`, which sets the body's `ActivationState` to `Deleted`, and there doesn't seem to be a good way to undo this with public API
- `World::add_rigid_body` takes a `RigidBody`, not a `RigidBodyHandle`, so it is difficult to avoid cloning the `RigidBody` every time it has to be re-added

A better option is be to modify the body's collision groups to disable all collision, but this is still ugly as nphysics and ncollide will still process it for collision and dynamics.

**Comment by Bendrien** [comment]
Perhaps you can set the object manually asleep, so its collision and dynamics won't be processed?

**Comment by Ralith** [comment]
I don't think that would be reliable, because sleeping objects are normally meant to be automatically awoken when something new interacts with them.

**Comment by sebcrozet** [comment]
Right now you don't have any alternative but removing/cloning/adding the rigid body. To address you use-case properly, I believe two features have to be added to nphysics:

1. Add rigid bodies without geometry (and/or allow the removal of the geometry from a rigid body). Those bodies would be affected by the dynamics but not the collisions.
2. Allow prescribed motions, i.e., give the ability to make the objects follow a path provided by the user. Other physics engines like Bullet call this "kinematic bodies".

At least the first one will be implemented with the re-design of nphysics. The second one should follow short after. In the mean time, I guess removing the rigid body and re-adding it is the only workaround.

**Comment by Ralith** [comment]
For now I'm just disabling collision so I don't have to worry about cloning and refreshing handles and so forth, which seems to work okay. Looking forward to the upcoming work!

**Comment by sebcrozet** [comment]
Starting with the version 0.8.0 of nphysics, it is possible to deactivate a body by setting its status to `BodyStatus::Disabled`. For example, with a rigid body with handle `body_handle`:

```rust
let mut rb = world.rigid_body_mut(body_handle).unwrap();
rb.set_status(BodyStatus::Disabled);
```

It can then be re-enabled by setting its status to something other than `Disabled`.
