### ISSUE TITLE
error[E0283]: type annotations required: cannot resolve `_: alga::general::real::Real`

### ISSUE THREAD

**Issue by ndarilek** [sebcrozet/nphysics#98]
Getting this error:

```
   Compiling tts v0.1.0 (file:///home/nolan/Projects/Wasm/tts)
error[E0283]: type annotations required: cannot resolve `_: alga::general::real::Real`
  --> src/ecs.rs:87:29
   |
87 |         let physics_world = nphysics2d::world::World::new();
   |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: required by `<ecs::nphysics2d::world::World<N>>::new`
```

Do I need to pull in another crate? I'm trying to store the `World` instance in a struct so my ECS can access it, and it seems like I'm missing an initialization step before I can do that. I've studied the examples, and they all seem to tweak the world and bodies in the same module, when what I want to do is just instantiate the world and set up bodies elsewhere.

Thanks.

**Comment by sebcrozet** [comment]
Closing this since the aswer from @Kerollmops is the way to solve this issue.
